MODEL:
  BACKBONE_TYPE: '3D'
  BACKBONE: 'S3D'
  PRETRAINED: False
  DROPOUT: 0.
  DEVICE: 'cuda'
  DEVICE_IDS: ('0, 1, 2, 3, 4, 5, 6, 7')


INPUT:
  BASE_SIZE: [112, 112]
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  MODALITY: 'RGB'
  SAMPLE_TYPE: 'dense'
  VIDEO_LENGTH: 16
  FLIP: True
  IMG_TMP: 'frame{:d}.jpg'
  TEMPORAL_JITTER: True

DATASET:
  NAME: 'kinetics-400'
  NUM_CLASS: 400
  VISUAL_ROOT_DIR: '/'
  TRAIN_SPLIT: '/'


DATALOADER:
  BATCH_SIZE: 32
  NUM_WORKERS: 24

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  USE_TRICK: False
  MAX_EPOCHS: 200
  BASE_LR: 0.06
  LR_SCHEDULER: 'step'
  LR_STEP: 20
  CLIP_GRADIENT: 'none'

  STEPS: [80, 120, 160]
  GAMMA: 0.1
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

APEX:  
  FLAG: False
  OPT_LEVEL: 'O1'
  LOCAL_RANK: 0

CHECKPOINT:
  RESUME: 'none'
  CHECKNAME: 'visual_model_s3d'
  CHECKPOINT_INTERVAL: 20
  NO_VAL: True
  FINETUNE: False
  PRINT_FREQ: 20

CONTRAST:
  MEM_TYPE: 'moco'
  NCE_K: 16384
  NCE_T: 0.07
  NCE_M: 0.5
  ALPHA: 0.999 